config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :categories,  only: [ :show ]
  resources :classifieds, only: [ :new, :create, :index, :show ] do
    get 'my', on: :collection

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :classifieds
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_attached_file :image, styles: {
    medium: '300x300',
    square: '200x200',
    thumb: '100x100',
  }

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :classifieds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_filter :authenticate_user!, only: [ :new, :create ]

  def index
    @classifieds = Classified.all
    @categories = Category.all
  end

  def new
    @classified = Classified.new
    @classified.build_category
  end

  def create
    @classified = current_user.classifieds.build(safe_classified_params)
    @classified.build_category(safe_category_params)

    if @classified.save
      redirect_to classified_path(@classified)
    else
      render 'new'
    end
  end

  def show
    @classified = Classified.find(params[:id])
  end

  def my
    @classifieds = current_user.Classified

    render 'index'
  end

  private

  def safe_classified_params
    params.require(:classified).permit(:title, :price, :description, :image)
  end

  def safe_category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classifieds/index.html.erb
<h1>Classifieds</h1>

<section class="col-md-8">
  <% @classifieds.each do |classified| %>
    <article class="well well-lg">
      <h2><%= classified.title %></h2>

      <p><%= classified.description %></p>

      <div><%="$#{classified.price}" %></div>
      <div><%= classified.category.name %> </div>
    </article>
  <% end %>
</section>

<section class="col-md-4">
  <article class="panel panel-primary">
    <div class="panel panel-heading">
      Categories
    </div>
    <ul class="panel panel-body categories">
      <% @categories.each do |category| %>
        <li ><h3><%= category.name %></h3></li>
      <% end %>
    </ul>
  </article>
</section>

app/views/classifieds/new.html.erb
<h1>Create a Classified</h1>

<%= form_for @classified, html: {multipart: true} do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= fields_for @classified.category do |category_form| %>
      <%= category_form.label :name %>
      <%= category_form.text_field :name, class: "form-control" %>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
   <%= form.label :image %>
   <%= form.file_field :image, class: 'form-control' %>
  </div>
  <%= form.submit "Create Classified", class: "btn btn-primary btn-lg" %>

<% end %>

app/views/classifieds/show.html.erb
<h1>Your Classified</h1>

<article>
  <h2><%= @classified.title %></h2>

  <p><%= @classified.description %></p>

  <div><%="$#{@classified.price}" %></div>
  <div><%= @classified.category.name %> </div>
  <img src='<%= @classified.image.url %>'>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Stuff Finder', root_url, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Log Out', destroy_user_session_path, method: 'delete' %>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to "Create New Classified", new_classified_path %>
<%= link_to "View List of Classifieds", classifieds_path %>